# Generated by Django 4.0.1 on 2022-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield'),
        ),
    ]
