# Generated by Django 4.0.1 on 2022-02-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='djangodbmodelsfieldscharfield', max_length=200),
        ),
    ]
