# Generated by Django 4.0.2 on 2022-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='home/images')),
            ],
        ),
    ]
